//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPMSysMessagesFailed
    {
        public int MessageID { get; set; }
        public string ProviderName { get; set; }
        public string Address { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int FailCount { get; set; }
        public System.DateTime RemoveAt { get; set; }
        public string Error { get; set; }
        public string Attachments { get; set; }
        public int ID { get; set; }
    }
}
