//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationUser
    {
        public int ID { get; set; }
        public string OpenID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Precision { get; set; }
        public Nullable<int> Event { get; set; }
    
        public virtual SubscribeUsers SubscribeUsers { get; set; }
    }
}
