//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JosonSenparcEntities : DbContext
    {
        public JosonSenparcEntities()
            : base("name=JosonSenparcEntities")
        {
            //this.Database.Initialize(false);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BPMProcNotifyRec> BPMProcNotifyRec { get; set; }
        public DbSet<BPMProcNotifyRecHis> BPMProcNotifyRecHis { get; set; }
        public DbSet<BPMSysMessagesQueue> BPMSysMessagesQueue { get; set; }
        public DbSet<LocationUser> LocationUser { get; set; }
        public DbSet<SubscribeUsers> SubscribeUsers { get; set; }
        public DbSet<BPMSysSettings> BPMSysSettings { get; set; }
        public DbSet<BPMSysMessagesFailed> BPMSysMessagesFailed { get; set; }
        public DbSet<BPMSysMessagesSucceed> BPMSysMessagesSucceed { get; set; }
    }
}
