//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribeUsers
    {
        public SubscribeUsers()
        {
            this.LocationUser = new HashSet<LocationUser>();
        }
    
        public int ID { get; set; }
        public string EmpID { get; set; }
        public Nullable<System.DateTime> SubscribeDate { get; set; }
        public string OpenID { get; set; }
        public string UnionID { get; set; }
        public string NickName { get; set; }
        public string Remark { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string GroupID { get; set; }
        public string Language { get; set; }
        public string Sex { get; set; }
        public string ImgSrc { get; set; }
        public Nullable<bool> IsPbulic { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<LocationUser> LocationUser { get; set; }
    }
}
