//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IJosonService")]
public interface IJosonService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IJosonService/DoWork", ReplyAction = "http://tempuri.org/IJosonService/DoWorkResponse")]
    string DoWork(string String);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IJosonService/DoWork", ReplyAction = "http://tempuri.org/IJosonService/DoWorkResponse")]
    System.Threading.Tasks.Task<string> DoWorkAsync(string String);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IJosonServiceChannel : IJosonService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class JosonServiceClient : System.ServiceModel.ClientBase<IJosonService>, IJosonService
{

    public JosonServiceClient()
    {
    }

    public JosonServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public JosonServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public JosonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public JosonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string DoWork(string String)
    {
        return base.Channel.DoWork(String);
    }

    public System.Threading.Tasks.Task<string> DoWorkAsync(string String)
    {
        return base.Channel.DoWorkAsync(String);
    }
}
