//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IJosonServices")]
public interface IJosonServices
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJosonServices/SendMsg", ReplyAction="http://tempuri.org/IJosonServices/SendMsgResponse")]
    bool SendMsg(string 接受者, string 微信内容, string 信息内容, int ID, bool isDebug);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJosonServices/SendMsg", ReplyAction="http://tempuri.org/IJosonServices/SendMsgResponse")]
    System.Threading.Tasks.Task<bool> SendMsgAsync(string 接受者, string 微信内容, string 信息内容, int ID, bool isDebug);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IJosonServicesChannel : IJosonServices, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class JosonServicesClient : System.ServiceModel.ClientBase<IJosonServices>, IJosonServices
{
    
    public JosonServicesClient()
    {
    }
    
    public JosonServicesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public JosonServicesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public JosonServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public JosonServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool SendMsg(string 接受者, string 微信内容, string 信息内容, int ID, bool isDebug)
    {
        return base.Channel.SendMsg(接受者, 微信内容, 信息内容, ID, isDebug);
    }
    
    public System.Threading.Tasks.Task<bool> SendMsgAsync(string 接受者, string 微信内容, string 信息内容, int ID, bool isDebug)
    {
        return base.Channel.SendMsgAsync(接受者, 微信内容, 信息内容, ID, isDebug);
    }
}
